; ------------------------------ styles ------------------------------

[HWiNFOTextStyle]
FontColor=255, 255, 255, 255
FontFace=Antipasto
FontSize=11
AntiAlias=1

[HWiNFOGraphStyle]
LineColor=#HWiNFOColor1#
LineColor2=#HWiNFOColor2#
LineColor3=#HWiNFOColor3#
LineColor4=#HWiNFOColor3#
PrimaryColor=255, 255, 255, 237
SolidColor=96, 96, 96, 96
W=720
H=70
AntiAlias=1

[HWiNFOGraphStyleSmall]
LineColor=#HWiNFOColor1#
LineColor2=#HWiNFOColor2#
LineColor3=#HWiNFOColor3#
LineColor4=#HWiNFOColor3#
PrimaryColor=255, 255, 255, 237
SolidColor=96, 96, 96, 96
W=360
H=70
AntiAlias=1

[HWiNFOTableHeaderStyle]
FontFace=Antipasto
FontColor=255, 255, 255, 255
FontSize=10
AntiAlias=1
Y=-90

; ------------------------------ skin header -----------------------------

[MeterTitle]
Meter=String
FontSize=30
FontFace=Antipasto
FontColor=225, 225, 225, 225
AntiAlias=1

; ------------------------------ variables ------------------------------

[Variables]
HWiNFOColor1=0, 255, 0, 255
HWiNFOColor2=255, 0, 0, 255
HWiNFOColor3=0, 225, 255, 255
HWiNFOColor4=255, 255, 255, 255
Column1=100
Column2=180
Column3=260

PhysicalMemoryUsed=0
PhysicalMemoryAvailable=1
PhysicalMemoryLoad=2
CoreClocks=28
CoreUsage=29
Core0T0Usage=3
Core0T1Usage=4
Core1T0Usage=5
Core1T1Usage=6
Core2T0Usage=7
Core2T1Usage=8
Core3T0Usage=9
Core3T1Usage=10
Core4T0Usage=11
Core4T1Usage=12
Core5T0Usage=13
Core5T1Usage=14
Core6T0Usage=15
Core6T1Usage=16
Core7T0Usage=17
Core7T1Usage=18
Core8T0Usage=19
Core8T1Usage=20
Core9T0Usage=21
Core9T1Usage=22
Core10T0Usage=23
Core10T1Usage=24
Core11T0Usage=25
Core11T1Usage=26
TotalCPUUsage=27
MemoryClock=30
CPUPackagePower=31
CoreTemperatures=32
Motherboard=33
CPU=34
Chassis2=35
PCH=37
AIOPump=38
Chipset=39
DriveTemperature=40
DriveRemainingLife=41
DriveFailure=42
DriveWarning=43
DriveTemperature=44
DriveRemainingLife=45
DriveFailure=46
DriveWarning=47
TotalActivity=48
TotalActivity=49
GPUTemperature=50
GPUMemoryJunctionTemperature=51
GPUFan1=52
GPUFan2=53
GPUPower=54
GPUClock=55
GPUMemoryClock=56
GPUCoreLoad=57
GPUMemoryControllerLoad=58
GPUMemoryAllocated=59
Chassis3=36
CurrentDLrate60
CurrentUPrate61